### DISCUSSION TITLE
Jaeger Operator - Not working for all namespaces

### DISCUSSION THREAD

**Discussion by PrateekKhatri** [jaegertracing/helm-charts#447] [General]
Hi Team,

I am trying to implement jaeger operator for all the namespaces available in the cluster, but it's not working, not able to see the services available in other namespaces into jaeger UI.

Is there anything I am missing to allow jaeger to work for all namespaces?? Please suggest.

**Below are the steps followed:**

```
helm install jaeger-operator jaegertracing/jaeger-operator --namespace observability --create-namespace --set rbac.clusterRole=true

kubectl apply -f jaeger.yaml
```

**jaeger.yaml -->** 
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
```

**Sample App Deployed in namespace app01:**

```
---
apiVersion: v1
kind: Service
metadata:
  name: jq-service-a
  labels:
    app: jq-service-a
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: jq-service-a
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jq-service-a
  annotations:
    sidecar.jaegertracing.io/inject: 'true'
  labels:
    app: jq-service-a
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jq-service-a
  template:
    metadata:
      labels:
        app: jq-service-a
        version: v1
    spec:
      containers:
        - name: app
          image: csantanapr/service-a-java-istio
          env:
            - name: JAEGER_ENDPOINT
              value: http://simplest-collector:14268/api/traces
            - name: SERVICE_FORMATTER
              value: jq-service-b
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: jq-service-b
  labels:
    app: jq-service-b
spec:
  ports:
    - port: 8081
      name: http
  selector:
    app: jq-service-b
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jq-service-b
  annotations:
    sidecar.jaegertracing.io/inject: 'true'
  labels:
    app: jq-service-b
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jq-service-b
  template:
    metadata:
      labels:
        app: jq-service-b
        version: v1
    spec:
      containers:
        - name: app
          image: csantanapr/service-b-java-istio
          env:
            - name: JAEGER_ENDPOINT
              value: http://simplest-collector:14268/api/traces
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
```
