### DISCUSSION TITLE
I cant apply the Jaeger CR, I got error

### DISCUSSION THREAD

**Discussion by wmashal** [jaegertracing/helm-charts#619] [Q&A]
What is wrong with my configurations ?
I am using helm 2.46.2

```yaml

apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: release-name-jaeger-operator-jaeger
  namespace: monitoring-prometheus
spec:
  strategy: production
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: https://vpc-jaeger-os-vpc-kjhkjhkjhkhkhkj.eu-central-1.es.amazonaws.com:443
        tls:
          enabled: false
    cmdlineParams:
      - --es.tls.enabled=false
      - --es.tls.skip-host-verify=false
    existingSecret: opensearch-secret
    existingSecretKey: ES_PASSWORD
    extraEnv:
      - name: ES_SERVER_URLS
        value: https://vpc-jaeger-os-vpc-kjhkjhkjhkhkhkj.eu-central-1.es.amazonaws.com
    scheme: https
    type: elasticsearch
    usePassword: true
    user: elastic

```

```
Error from server (BadRequest): error when creating "test.yaml": Jaeger in version "v1" cannot be handled as a Jaeger: strict decoding error: unknown field "spec.storage.cmdlineParams", unknown field "spec.storage.existingSecret", unknown field "spec.storage.existingSecretKey", unknown field "spec.storage.extraEnv", unknown field "spec.storage.scheme", unknown field "spec.storage.usePassword", unknown field "spec.storage.user"
```

Please help ?
