### ISSUE TITLE
[jaeger] yaml parse error when using custom cassandra or elasticsearch environment variables

### ISSUE THREAD

**Issue by mrparkers** [jaegertracing/helm-charts#100]
you can reproduce using the following `values.yaml` file:

```yaml
storage:
  type: elasticsearch
  elasticsearch:
    env:
      ES_TLS_SKIP_HOST_VERIFY: true
```

and run

```bash
helm template jaegertracing/jaeger --version 0.27.2 -f values.yaml
```
