### ISSUE TITLE
Error: container has runAsNonRoot and image will run as root

### ISSUE THREAD

**Issue by msschl** [jaegertracing/helm-charts#105]
Deploying jaeger results in the following error:
```
Error: container has runAsNonRoot and image will run as root
```

Deploy script:
```sh
helm upgrade jaeger vendor/jaeger-helm-charts/charts/jaeger \
    -n monitoring \
    -f vendor/jaeger-helm-charts/charts/jaeger/values.yaml \
    -f src/monitoring/jaeger/values.yaml \
    -i $@
```

`src/monitoring/jaeger/values.yaml`:
```yaml
# Default values for jaeger are specified in
# vendor/jaeger-helm-charts/charts/jaeger/values.yaml

provisionDataStore:
  cassandra: false
  elasticsearch: false
  kafka: false

storage:
  type: elasticsearch
  elasticsearch:
    scheme: http
    # NOTE(msschl): cluster internal only. Not reachable from outside...
    host: elasticsearch-master.elasticsearch.svc.k8s-cluster.company.xyz
    port: 9200
    usePassword: false

query:
  ingress:
    enabled: true
    hosts:
      - tracing.kube-dev.company.xyz
    annotations:
      kubernetes.io/ingress.class: "nginx-ingress"
    tls:
      - secretName: "public/company-tls"
        hosts:
          - tracing.kube-dev.company.xyz

# QUESTION(msschl): Enable?
esIndexCleaner:
  enabled: false
```

We do have a default psp policy in place and its bound to the deployed jaeger pods:
```yaml
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: default-restricted
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'runtime/default'
    apparmor.security.beta.kubernetes.io/allowedProfileNames: 'runtime/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'runtime/default'
    apparmor.security.beta.kubernetes.io/defaultProfileName:  'runtime/default'
spec:
  allowedCapabilities: []
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    - ALL
  volumes:
    - 'configMap'
    - 'secret'
    - 'persistentVolumeClaim'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'MustRunAsNonRoot'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  readOnlyRootFilesystem: true
```

Full description from agent pod:
```sh
$ kubectl -n monitoring describe po jaeger-agent-ndzwz
Name:         jaeger-agent-ndzwz
Namespace:    monitoring
Priority:     0
Node:         lxkubenode02/172.18.2.93
Start Time:   Fri, 15 May 2020 17:36:33 +0200
Labels:       app.kubernetes.io/component=agent
              app.kubernetes.io/instance=jaeger
              app.kubernetes.io/name=jaeger
              controller-revision-hash=6ff9dcbc57
              pod-template-generation=1
Annotations:  cni.projectcalico.org/podIP: 10.244.206.69/32
              cni.projectcalico.org/podIPs: 10.244.206.69/32
              container.apparmor.security.beta.kubernetes.io/jaeger-agent: runtime/default
              kubernetes.io/psp: default-restricted
              seccomp.security.alpha.kubernetes.io/pod: runtime/default
Status:       Pending
IP:           10.244.206.69
IPs:
  IP:           10.244.206.69
Controlled By:  DaemonSet/jaeger-agent
Containers:
  jaeger-agent:
    Container ID:
    Image:          jaegertracing/jaeger-agent:1.17.1
    Image ID:
    Ports:          5775/UDP, 6831/UDP, 6832/UDP, 5778/TCP, 14271/TCP
    Host Ports:     0/UDP, 0/UDP, 0/UDP, 0/TCP, 0/TCP
    State:          Waiting
      Reason:       CreateContainerConfigError
    Ready:          False
    Restart Count:  0
    Liveness:       http-get http://:admin/ delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get http://:admin/ delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      REPORTER_GRPC_HOST_PORT:  jaeger-collector:14250
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from jaeger-agent-token-s2hzt (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  jaeger-agent-token-s2hzt:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  jaeger-agent-token-s2hzt
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/pid-pressure:NoSchedule
                 node.kubernetes.io/unreachable:NoExecute
                 node.kubernetes.io/unschedulable:NoSchedule
Events:
  Type     Reason     Age               From                   Message
  ----     ------     ----              ----                   -------
  Normal   Scheduled  <unknown>         default-scheduler      Successfully assigned monitoring/jaeger-agent-ndzwz to lxkubenode02
  Normal   Pulling    6s (x4 over 25s)  kubelet, lxkubenode02  Pulling image "jaegertracing/jaeger-agent:1.17.1"
  Normal   Pulled     5s (x4 over 24s)  kubelet, lxkubenode02  Successfully pulled image "jaegertracing/jaeger-agent:1.17.1"
  Warning  Failed     5s (x4 over 24s)  kubelet, lxkubenode02  Error: container has runAsNonRoot and image will run as root
```
