### ISSUE TITLE
cassandra.nodeSelector ignored

### ISSUE THREAD

**Issue by schmurfy** [jaegertracing/helm-charts#107]
I am trying to install the whole jaeger stack on a specific node pool but cassandra pods are created outside of this pool.

Here is my values.yaml:
```yaml
collector:
  nodeSelector: &selector
    pool: jaeger

query:
  nodeSelector: *selector

cassandra:
  nodeSelector: *selector
```

`query` and `collector` are correctly created on the pool

**Comment by naseemkullah** [comment]
Hi @schmurfy so this is due to the way the dependency cassandra chart works, it has a somewhat custom approach to the values nesting `nodeSelector` one level deeper: https://github.com/helm/charts/blob/39777352ebc9085cd0d4ed928d4b173f26244c7f/incubator/cassandra/values.yaml#L105-L109

**Comment by schmurfy** [comment]
Thanks, I read what you linked but I am not sure what I need to write, is it this ?
```yaml
collector:
  nodeSelector: &selector
    pool: jaeger

query:
  nodeSelector: *selector

selector:
  nodeSelector:
    cassandra: *selector
```

**Comment by naseemkullah** [comment]
Try

```yaml
cassandra:
  selector:
    nodeselector: *selector
```

To get what you are supposed to write you would need to look at the chart being configured's quirks: https://github.com/helm/charts/blob/39777352ebc9085cd0d4ed928d4b173f26244c7f/incubator/cassandra/templates/statefulset.yaml#L37-L39

**Comment by schmurfy** [comment]
Thanks but it still does not work.

I tried this:
```yaml
collector:
  nodeSelector: &selector
    pool: jaeger

query:
  nodeSelector: *selector

cassandra:
  selector:
    nodeselector: *selector
```

I also tried the following which is in the cassandra chart readme without more luck:
```yaml
nodes:
  enabled: true
  selector:
    nodeSelector: *selector
```

and:
```yaml
cassandra:
  nodes:
    enabled: true
    selector:
      nodeSelector: *selector
```

I really tried to understand what I was supposed to write by looking at the templates but this is totally cryptic to me :/
query & collector get their node selector correctly set but cassandra never got one...

**Comment by schmurfy** [comment]
after even more attempts from a colleage after I gave up he finally found the working version:
```yaml
cassandra:
  selector:
    nodeSelector:
      pool: jaeger
```

The more I use helm and the more amazed I am this thing even exists, it feels like a bag of junk stitched together...
