### ISSUE TITLE
[jaeger-operator] Helm chart does not create pvcs when using all-in-one badger storage

### ISSUE THREAD

**Issue by appanycd** [jaegertracing/helm-charts#132]
```yaml
jaeger:
  create: true
  spec:
    strategy: allInOne
    ...
    storage:
      type: badger
      options:
        badger:
          ephemeral: false
          directory-key: /badger/key
          directory-value: /badger/data
    volumeMounts:
    - name: jaeger
      mountPath: /badger
    volumes:
    - name: jaeger
      persistentVolumeClaim:
        claimName: jaeger-pvc # jaeger-pvc should be created
```

I think helm chart can support deploying pvc:
```yaml
jaeger:
  create: true
  ...
badger:
  enabled: true
  persistence:
  ...
```
