### ISSUE TITLE
[jaeger] extraEnv variables need to be passed as strings

### ISSUE THREAD

**Issue by user-name-is-taken** [jaegertracing/helm-charts#153]
This section

```
storage:
  cassandra:
    extraEnv: []
      # - name: CASSANDRA_SERVERS
      #   value: cassandra
      # - name: CASSANDRA_PORT
      #   value: 9042
      # - name: CASSANDRA_KEYSPACE
      #   value: jaeger_v1_test
      # - name: CASSANDRA_TLS_ENABLED
      #   value: false
```

Should be

```
storage:
  cassandra:
    extraEnv: []
      # - name: CASSANDRA_SERVERS
      #   value: cassandra
      # - name: CASSANDRA_PORT
      #   value: "9042"
      # - name: CASSANDRA_KEYSPACE
      #   value: jaeger_v1_test
      # - name: CASSANDRA_TLS_ENABLED
      #   value: "false"
```

because env vars have to be strings as discussed [here](https://github.com/helm/helm/issues/4775#issuecomment-431171187)
