### ISSUE TITLE
[jaeger] Set cassandra.config.seed_size=2 and cassandra.config.cluster_size=3

### ISSUE THREAD

**Issue by user-name-is-taken** [jaegertracing/helm-charts#155]
I'm not a cassandra expert, but with `cassandra.config.seed_size=1` I was getting errors saying *unable to gossip with peers*. When I added peers as you can see in the following config, I no longer get this error.

```
cassandra:
  config:
    cluster_size: 3
    seed_size: 2
```
