### ISSUE TITLE
Feature - Add generic or extended how kubernetes secrets can be used with env vars

### ISSUE THREAD

**Issue by bogdan-matei** [jaegertracing/helm-charts#169]
### Description

Currently the only property that supports the usage of k8s secrets as environment variable is the password by enabling the **existingSecret** and **existingSecretKey**. This is then processed as seen in [_helpers.tpl](https://github.com/jaegertracing/helm-charts/blob/1ca613f6ffb0205c145ef577792bf6264b93ca6c/charts/jaeger/templates/_helpers.tpl#L321). 
At the moment there isn't a generic way of using secrets aside the password, for example passing the user and host as secrets.

### Proposal

_helpers.tpl should contain a code block which sets the values of the environment variables from the secret itself.

E.g.:
If an object contains **secret** then take the environment value is taken from the secret. In this case the ES_SERVER_URLS.

```
{{- if .Values.storage.elasticsearch.secret -}}
- name: ES_SERVER_URLS
  valueFrom:
    secretKeyRef:
      name: {{ .Values.storage.elasticsearch.secret.host.existingSecret }}
      key: {{ default "host" .Values.storage.elasticsearch.secret.host.existingSecretKey }}
{{- else -}}
- name: ES_SERVER_URLS
  value: {{ include "elasticsearch.client.url" . }}
{{- end -}}
```
