### ISSUE TITLE
Mismatch in jaeger-operator helm chart service selector labels

### ISSUE THREAD

**Issue by hagaibarel** [jaegertracing/helm-charts#171]
Hi, 

In the `jaeger-opeator` helm chart, there's a mismatch between the service selector labels and the actual pod labels, which causes the service to be created without proper endpoints. 

[service](https://github.com/jaegertracing/helm-charts/blob/master/charts/jaeger-operator/templates/service.yaml#L13-L15):

```yaml
  selector:
    app.kubernetes.io/name: {{ include "jaeger-operator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
```

[pod](https://github.com/jaegertracing/helm-charts/blob/master/charts/jaeger-operator/templates/deployment.yaml#L15-L16):

```yaml
      labels:
{{ include "jaeger-operator.labels" . | indent 8 }}
```

The labels section in [_helpers.tpl](https://github.com/jaegertracing/helm-charts/blob/master/charts/jaeger-operator/templates/_helpers.tpl#L45-L48):

```yaml
{{/* Generate basic labels */}}
{{- define "jaeger-operator.labels" }}
app.kubernetes.io/name: {{ include "jaeger-operator.name" . }}
{{- end }}
```
