### ISSUE TITLE
[jaeger-operator] unknown field "additionalPrinterColumns", "subresources", "version" in in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec

### ISSUE THREAD

**Issue by jjangga0214** [jaegertracing/helm-charts#193]
It seems there're some inappropriate configuration in CRD.

**Reproduction**:
```shell
helm pull jaegertracing/jaeger-operator --version 2.18.3 --untar --destination /tmp/foo && \ 
kubectl apply -f /tmp/foo/jaeger-operator/crds
```

**Output**:
```
error: error validating "/tmp/foo/jaeger-operator/crds/crd.yaml": error validating data: [ValidationError(CustomResourceDefinition.spec): unknown field "additionalPrinterColumns" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): unknown field "subresources" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): unknown field "version" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec]; if you choose to ignore these errors, turn validation off with --validate=false
```

**Info**:
```shell
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-23T02:22:53Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by tricky42** [comment]
I ran into the same problem as @jjangga0214 when trying to deploy 2.18.3 using ArgoCD.

**Comment by diranged** [comment]
Seeing this as well.. is it this PR? https://github.com/jaegertracing/helm-charts/commit/0badead55a49923e94369033ff4343126ee568c7

**Comment by elkh510** [comment]
any updates ?

**Comment by ClumsyPotato** [comment]
Same problem T.T

**Comment by AljoschaP** [comment]
I tried to fix the CRD manually. I moved additionalPrinterColums (as specified in the [docs](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/)) and deleted version and subresources.

Old version (not working):

```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: jaegers.jaegertracing.io
  annotations:
    "helm.sh/hook": crd-install
    "helm.sh/hook-delete-policy": "before-hook-creation"
  labels:
    app: jaeger-operator
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    description: Jaeger instance's status
    name: Status
    type: string
  - JSONPath: .status.version
    description: Jaeger Version
    name: Version
    type: string
  group: jaegertracing.io
  names:
    kind: Jaeger
    listKind: JaegerList
    plural: jaegers
    singular: jaeger
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
```

New version(working):

```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: jaegers.jaegertracing.io
  annotations:
    "helm.sh/hook": crd-install
    "helm.sh/hook-delete-policy": "before-hook-creation"
  labels:
    app: jaeger-operator
spec:
  group: jaegertracing.io
  names:
    kind: Jaeger
    listKind: JaegerList
    plural: jaegers
    singular: jaeger
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      additionalPrinterColumns:
        - jsonPath: .status.phase
          description: Jaeger instance's status
          name: Status
          type: string
        - jsonPath: .status.version
          description: Jaeger Version
          name: Version
          type: string
```
