### ISSUE TITLE
[jaeger] Spark job not working with elasticsearch storage

### ISSUE THREAD

**Issue by kedith** [jaegertracing/helm-charts#200]
I am using a helm chart which uses jaeger as an upstream chart. The storage I use is elasticsearch. I tried to enable the spark depenencies job adding the following lines to my _values.yaml_:
```yaml
spark:
  enabled: true
```
and got this error trying to install the chart with my custom values:
```
Error: template: i3-tracing-helm/charts/jaeger/templates/spark-cronjob.yaml:53:26: executing "i3-tracing-helm/charts/jaeger/templates/spark-cronjob.yaml" at <include "cassandra.contact_points" .>: error calling include: template: i3-tracing-helm/charts/jaeger/templates/_helpers.tpl:230:14: executing "cassandra.contact_points" at <.Values.provisionDataStore.cassandra>: nil pointer evaluating interface {}.cassandra
helm.go:81: [debug] template: i3-tracing-helm/charts/jaeger/templates/spark-cronjob.yaml:53:26: executing "i3-tracing-helm/charts/jaeger/templates/spark-cronjob.yaml" at <include "cassandra.contact_points" .>: error calling include: template: i3-tracing-helm/charts/jaeger/templates/_helpers.tpl:230:14: executing "cassandra.contact_points" at <.Values.provisionDataStore.cassandra>: nil pointer evaluating interface {}.cassandra
```
The problem is that the cassandra contact_points in the _spark-cronjob.yaml_ are always set, regardless of the storage type, resulting in a nil pointer error when a different storage type is used. Here is the snippet of the  _spark-cronjob.yaml_:
```yaml
            env:
              - name: STORAGE
                value: {{ .Values.storage.type }}
              {{- include "storage.env" . | nindent 14 }}
            {{- if .Values.spark.extraEnv }}
              {{- toYaml .Values.spark.extraEnv | nindent 14 }}
            {{- end }}
              - name: CASSANDRA_CONTACT_POINTS
                value: {{ include "cassandra.contact_points" . }}
```
I tried commenting out CASSANDRA_CONTACT_POINTS and the spark job worked as expected. I tested all of this on the jaeger 0.39.1 chart.
