### ISSUE TITLE
COLLECTOR_ZIPKIN_HTTP_PORT is deprecated in v1.22.0

### ISSUE THREAD

**Issue by uqix** [jaegertracing/helm-charts#212]
https://github.com/jaegertracing/jaeger/issues/2864#issuecomment-791451930

So we need to replace `COLLECTOR_ZIPKIN_HTTP_PORT` with `COLLECTOR_ZIPKIN_HOST_PORT` in `templates/collector-deploy.yaml`:
```yaml
        env:
          {{- if .Values.collector.service.zipkin }}
          - name: COLLECTOR_ZIPKIN_HTTP_PORT
            value: {{ .Values.collector.service.zipkin.port | quote }}
          {{- end }}
```
