### ISSUE TITLE
Operator fails with: failed to store the running status into the current CustomResource

### ISSUE THREAD

**Issue by larsrnielsen** [jaegertracing/helm-charts#224]
Installation of Jaeger operator via Helm is successful in the sense that pods are created and running. However, when I look at the logs below I see errors. How can I fix this?

Helm version for Operator: 2.19.1

```
jaegerOperator:
  enabled: true
  values:
    jaeger:
      create: true
    # enabled: true
    # values:
      spec:
        # provisionDataStore:
        #   cassandra: false
        #   elasticsearch: false
        #   kafka: false
        strategy: production
        
        ingress:
          enabled: true
          annotations:
            alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-central-1:123456789012:certificate/2e67h65a-930a-4f7c-84x3-67bb22jba74
            alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}, {"HTTP":80}]'
            alb.ingress.kubernetes.io/backend-protocol: HTTP
            alb.ingress.kubernetes.io/scheme: internal
            alb.ingress.kubernetes.io/group.name: monitoring
            alb.ingress.kubernetes.io/security-groups: cms_dev-alb_private
            alb.ingress.kubernetes.io/target-type: ip
            kubernetes.io/ingress.class: alb
          hosts:
            - jaeger.something.com
        collector:
          minReplicas: 3
          maxReplicas: 5
        resources:
          requests:
            memory: "254Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "500m"
        storage:
          type: elasticsearch
          options:
            es:
              server-urls: http:/something.com:9200
              index-prefix: cms-eks-jaeger-dev-7
```

```
time="2021-03-24T13:50:52Z" level=info msg=Versions arch=amd64 identity=monitoring.jaeger-jaeger-operator jaeger=1.21.0 jaeger-operator=v1.21.2 operator-sdk=v0.18.2 os=linux version=go1.14.12
I0324 13:50:53.750024       1 request.go:621] Throttling request took 1.042001102s, request: GET:https://172.20.0.1:443/apis/jaegertracing.io/v1?timeout=32s
time="2021-03-24T13:51:02Z" level=info msg="Consider running the operator in a cluster-wide scope for extra features"
I0324 13:51:04.038298       1 request.go:621] Throttling request took 1.344815296s, request: GET:https://172.20.0.1:443/apis/vpcresources.k8s.aws/v1beta1?timeout=32s
time="2021-03-24T13:51:04Z" level=info msg="Auto-detected the platform" platform=kubernetes
time="2021-03-24T13:51:04Z" level=info msg="Auto-detected ingress api" ingress-api=networking
time="2021-03-24T13:51:04Z" level=info msg="Automatically adjusted the 'es-provision' flag" es-provision=no
time="2021-03-24T13:51:04Z" level=info msg="Automatically adjusted the 'kafka-provision' flag" kafka-provision=no
time="2021-03-24T13:51:09Z" level=warning msg="could not create ServiceMonitor object" error="servicemonitors.monitoring.coreos.com \"jaeger-jaeger-operator-metrics\" already exists"
time="2021-03-24T13:51:09Z" level=error msg="failed to store the running status into the current CustomResource" error="jaegers.jaegertracing.io \"jaeger-jaeger-operator-jaeger\" not found" execution="2021-03-24 13:51:09.477766206 +0000 UTC" instance=jaeger-jaeger-operator-jaeger namespace=monitoring
time="2021-03-24T13:51:15Z" level=error msg="failed to store the running status into the current CustomResource" error="jaegers.jaegertracing.io \"jaeger-jaeger-operator-jaeger\" not found" execution="2021-03-24 13:51:10.791623294 +0000 UTC" instance=jaeger-jaeger-operator-jaeger namespace=monitoring
time="2021-03-24T13:51:16Z" level=error msg="failed to store the running status into the current CustomResource" error="jaegers.jaegertracing.io \"jaeger-jaeger-operator-jaeger\" not found" execution="2021-03-24 13:51:16.006061858 +0000 UTC" instance=jaeger-jaeger-operator-jaeger namespace=monitoring
time="2021-03-24T13:51:17Z" level=error msg="failed to store the running status into the current CustomResource" error="jaegers.jaegertracing.io \"jaeger-jaeger-operator-jaeger\" not found" execution="2021-03-24 13:51:17.208759524 +0000 UTC" instance=jaeger-jaeger-operator-jaeger namespace=monitoring
time="2021-03-24T13:51:26Z" level=error msg="failed to store the running status into the current CustomResource" error="jaegers.jaegertracing.io \"jaeger-jaeger-operator-jaeger\" not found" execution="2021-03-24 13:51:18.409333264 +0000 UTC" instance=jaeger-jaeger-operator-jaeger namespace=monitoring
time="2021-03-24T13:51:27Z" level=error msg="failed to store the running status into the current CustomResource" error="jaegers.jaegertracing.io \"jaeger-jaeger-operator-jaeger\" not found" execution="2021-03-24 13:51:27.639859735 +0000 UTC" instance=jaeger-jaeger-operator-jaeger namespace=monitoring
```
