### ISSUE TITLE
Ingester adds env variables for kafka consumer but not producer brokers

### ISSUE THREAD

**Issue by matt-psaltis** [jaegertracing/helm-charts#227]
When the ingester boots it logs

msg":"Kafka factory","producer builder":{"Brokers":["127.0.0.1:9092"]

Kafka is not hosted in the ingester pod and so this crashes the pod.

I believe that the ingester deploy should either:
1. Additionally include KAFKA_PRODUCER_BROKERS into the environment variables
2. Replace KAFKA_CONSUMER_BROKERS with KAFKA_PRODUCER_BROKERS

See: https://github.com/jaegertracing/helm-charts/blob/aee420f6361775c326e0d258184ac79a1cd4153d/charts/jaeger/templates/ingester-deploy.yaml#L69

As a workaround, I tried the following custom values block when running the helm chart:

```
ingester:
  enabled: true
  extraEnv:
    - name: KAFKA_PRODUCER_BROKERS
      value: jaeger-kafka-headless:9093
```

This correctly connects to kafka.
