### ISSUE TITLE
[jaeger-operator] chart enhancement extra args for operator

### ISSUE THREAD

**Issue by vd-rd** [jaegertracing/helm-charts#232]
Hello,
After reviewing the install docs, two options are mentioned for interacting with strimzi and ECK.
In order to make use of them the args for the operator need to be edited from
```yaml
spec:
  containers:
     args: 
       - start
```
to 
```yaml
spec:
  containers:
     args: 
       - start
       - '--es-provision=yes'
       - '--kafka-provision=yes'
```
However, the means to add this as helm arguments is not implemented in the chart template.

My suggestion would be an extraArgs section for the chart, like
```yaml
args:
  - start
    {{- range $key, $value := .Values.extraArgs }}
    {{- if $value }}
    - --{{ $key }}={{ $value }}
    {{- else }}
    - --{{ $key }}
    {{- end }}
{{- end }}
```

Let me know if this makes sense and you would consider implementing this 😃
