### ISSUE TITLE
How to configure the helm chart with AWS Elasticsearch?

### ISSUE THREAD

**Issue by Spritekin** [jaegertracing/helm-charts#237]
Hi,

This post started as a request for help but as I found the solution I will turn it into a guide. I was searching around how to configure the jaeger helm chart to work with AWS Elasticsearch as it kept failing with a message like this causing a crashloop.

```
"msg":"Failed to init storage factory",
"error":"failed to create primary Elasticsearch client: health check timeout: no Elasticsearch node available"
```

So this is my successful configuration.

My jaeger helm chart is cconigured as:
```
    storage:
      type: elasticsearch
      elasticsearch:
        host: xxxxxxxxx-7slrs2rsxqg763fmisjwlnvzay.ap-southeast-2.es.amazonaws.com
        port: 80
        scheme: http
        user: ""
        usePassword: false
    provisionDataStore:
      cassandra: false
      elasticsearch: false
```

Check your elasticsearch is accessible from the Kube cluster in the same namespace you will run jaeger. 

```
>> kubectl exec -ti some_pod_in_target_namespace -- sh
$ curl http://xxxxxxxxx-7slrs2rsxqg763fmisjwlnvzay.ap-southeast-2.es.amazonaws.com:80
{
  "name" : "76b2ed740ece0d3e52658481e171a05a",
  "cluster_name" : "accountid:xxxxxxx",
  "cluster_uuid" : "PcxAzwhORtGIi2AiRAExtQ",
  "version" : {
    "number" : "7.8.0",
    "build_flavor" : "oss",
    "build_type" : "tar",
    "build_hash" : "unknown",
    "build_date" : "2021-01-15T06:15:47.944536Z",
    "build_snapshot" : false,
    "lucene_version" : "8.5.1",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```

Now, you need to make sure the ES policies are quite open for your user. In this case I allow every user but you can restrict to some specific users. I couldn't find a doc that describes the list of permissions required by jaeger so I just selected es:* but maybe someone can limit this list.
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "AWS": "*"   <<<< specify your users here
      },
      "Action": [
        "es:*"        <<<< specify your permissions
      ],
      "Resource": [
        "your_domain_arn/*",
        "your_domain_arn"
      ]
    }
  ]
}
```

That's all. Hope someone finds it useful.
