### ISSUE TITLE
Missing app.kubernetes.io/instance label from _helpers.tpl

### ISSUE THREAD

**Issue by ethernoy** [jaegertracing/helm-charts#247]
I want to raise an issue about the jaeger-operator helm chart.

In `_helpers.tpl`, the following code snippet insert labels for jaeger-operator deployment:

```
{{/* Generate basic labels */}}
{{- define "jaeger-operator.labels" }}
app.kubernetes.io/name: {{ include "jaeger-operator.name" . }}
{{- end }}
```

Comparing to `service.yaml`:

```
selector:
    app.kubernetes.io/name: {{ include "jaeger-operator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: {{ .Values.service.type }}
```

It seems the label `app.kubernetes.io/instance` is missing from _helpers.tpl. As a result, the generated metrics service cannot correctly select the jaeger-operator pod to expose its metrics.

![image](https://user-images.githubusercontent.com/15870761/118098984-36144180-b407-11eb-8f5b-803898a7ba1e.png)

I wonder if this is a bug? If so I am happy to create a PR to fix it :)
