### ISSUE TITLE
[jaeger] deploying Ingester

### ISSUE THREAD

**Issue by arpitjindal97** [jaegertracing/helm-charts#27]
We should also add ingester deployment

**Comment by naseemkullah** [comment]
We should allow the end user to either provide existing Streaming Backend (Kafka) values, or for those who just want to get going and don't have kafka, we should add an option to provision it via https://github.com/confluentinc/cp-helm-charts/tree/master/charts/cp-kafka (That chart might need some TLC, but it's backed by Confluent so that's good).

Furthermore, I think we should specify that the backendtype is Kafka, and leave it open to it being something else in the future (NATS, Redis(Streams), etc.)

**Comment by arpitjindal97** [comment]
We can add config for provisioning Kafka for the user who don't have it and also users can provide details of exisiting kafka. 
Ingester has support for kafka only. So, I think there is no point in allowing user to choose between kafka and other streaming services. (maybe in future when support for other is available)

Kafka enablement will be decided based on ingester

```
ingester:
  enabled: false
  annotations: {}
  image: jaegertracing/jaeger-ingester
  pullPolicy: IfNotPresent
  cmdlineParams: {}
  service:
    type: ClusterIP
  extraConfigmapMounts: []
```

Ingester will be `enabled: false` by default. If user has enabled it then only kafka configs will apply over `collector`.

For provisioning of kafka, It will be totally based provision value. Something like this
```
provisionDataStore:
  cassandra: true
  elasticsearch: false
  kafka: false
```

This is how I have tackled this situation :)
