### ISSUE TITLE
Jaeger Operator : Failed to store the failed status into the current CustomResource after the recon ciliation" error="jaegers.jaegertracing.io \"jaeger\" not found"

### ISSUE THREAD

**Issue by advissor** [jaegertracing/helm-charts#272]
**Describe the bug**

**To Reproduce**
1.  Install Jaeger operator via helm chart
2. Create Jaeger tracing config

```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
spec:
  strategy: production
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://elasticsearch:9200
        username: yyy
        password: xx
```
3. Jaeger components initialise successfully

But, in logs of the Operator it shows continuously the errors 

```
 level=error msg="failed to store the failed status into the current CustomResource after the recon
ciliation" error="jaegers.jaegertracing.io \"jaeger\" not found" jaeger namespace=default
level=error msg="failed to apply the changes" error="timed out waiting for the condition" instance=jaeger namespace=default
```

**Expected behavior**
No errors in Operator logs, as the components were created successfully and resource exists in the default namespace

**Screenshots**

**Version (please complete the following information):**
 - OS: kubernetes , 1.20, eks
 - Jaeger version: jaegertracing/jaeger-operator:1.24.0
 - Deployment: kubernetes, helm chart

**What troubleshooting steps did you try?**
Tried to rename the jaeger to some other name, as seen people seen similar errors when jaeger created Service Account with the same name as the jaeger object and that somehow cause the error.
