### ISSUE TITLE
Update chart to latest jagger release

### ISSUE THREAD

**Issue by farlop** [jaegertracing/helm-charts#295]
## Requirement - what kind of business use case are you trying to solve?

Install a jagger release using the Helm chart that supports Cassandra 4

## Problem - what in Jaeger blocks you from solving the requirement?

Cassandra 4 support was added in Jaegger 1.26, but the chart currently installs 1.22, as the version is tied to the chart.appVersion field. This field cannot be overriden so, it's not possible (AFAIK) to force to deploy another version of Jaegger using the helm chart.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Review this helm chart in order to use the latest version of Jaegger.

**Comment by mehta-ankit** [comment]
Closing this issue as this PR upgrade the chart to use 1.28.0 Jaeger release: https://github.com/jaegertracing/helm-charts/pull/314

**Comment by farlop** [comment]
Just an additional question. Is it possible that  the way to define the ingress resource for Jaeger has changed? My previous values.yml is no longer valid and I had to comment all that section

```
                 query:
                    ingress:
                      enabled: true
                      annotations:
                        kubernetes.io/ingress.class: nginx
                      hosts:
                      - $(DNS)
                      tls:
                      - secretName: tls
                        hosts:
                        - $(DNS)
                    basePath: /jaeger
```

I haven't found any sample of how to define YAML for ingress resource.

Could you please provide some guidance?
