### ISSUE TITLE
cassandra-schema-job can't work when not use default port 

### ISSUE THREAD

**Issue by a2659802** [jaegertracing/helm-charts#297]
**Describe the bug**

cassandra-schema-job can not connect to cassandra when you change the default port 9042.
when I install the chart with values like this
```
storage:
  # allowed values (cassandra, elasticsearch)
  type: cassandra
  cassandra:
    host: 10.113.68.16
    port: 49154
```
and i actually get the env is like this:
```
 env:
          
          - name: CASSANDRA_SERVERS
            value: 10.113.68.16
          - name: CASSANDRA_PORT
            value: "49154"
          - name: CASSANDRA_KEYSPACE
            value: jaeger_v1_test
          - name: CASSANDRA_USERNAME
            value: user
          - name: CASSANDRA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: istio-test-jaeger-cassandra
                key: password
          - name: CQLSH_HOST
            value: 10.113.68.16
          - name: DATACENTER
            value: "dc1"
          - name: KEYSPACE
            value: jaeger_v1_test
```
I go through the templates files and the docker.sh, found that the script require CQLSH_PORT env, but the YAML not provide it.
so it try the default 9042 and certainly failed

**To Reproduce**
1.  install with custom cassandra host and port
2.
3.

**Expected behavior**
connect with custom host and port.

**Screenshots**

Connection error: ('Unable to connect to any servers', {'10.113.68.16:9042': ConnectionRefusedError(111, "Tried connecting to [('10.113.68.16', 9042)]. Last error: Connection refused")})
Cassandra is still not up at 10.113.68.16:9042. Waiting 1 second.
Connection error: ('Unable to connect to any servers', {'10.113.68.16:9042': ConnectionRefusedError(111, "Tried connecting to [('10.113.68.16', 9042)]. Last error: Connection refused")})
Cassandra is still not up at 10.113.68.16:9042. Waiting 1 second.
Connection error: ('Unable to connect to any servers', {'10.113.68.16:9042': ConnectionRefusedError(111, "Tried connecting to [('10.113.68.16', 9042)]. Last error: Connection refused")})
Cassandra is still not up at 10.113.68.16:9042. Waiting 1 second.

**Version (please complete the following information):**
 - OS: Centos7
 - Jaeger version: 1.27.0
 - Deployment: Kubernetes1.16

**What troubleshooting steps did you try?**
Try to follow https://www.jaegertracing.io/docs/latest/troubleshooting/ and describe how far you were able to progress and/or which steps did not work.

**Additional context**
it's easy to fix with adding following code to cassandra-schema-job.yaml
```
- name: CQLSH_PORT
  value: {{ .Values.storage.cassandra.port | quote }}
```
