### ISSUE TITLE
[jaeger] Agent service specific NodePort

### ISSUE THREAD

**Issue by zemkogabor** [jaegertracing/helm-charts#328]
## Requirement - what kind of business use case are you trying to solve?

Specific node port numbers for agent service.

## Problem - what in Jaeger blocks you from solving the requirement?

Currently a random node port number is generated for the Jaeger agent service when using the NodePort service type.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Modify `charts/jaeger/templates/agent-svc.yml` with the following snippet or something similar:

```
spec:
  ports:
  - name: zipkin-compact
    port: {{ .Values.agent.service.zipkinThriftPort }}
    protocol: UDP
    targetPort: zipkin-compact
{{- if and (eq .Values.agent.service.type "NodePort") (.Values.agent.service.zipkinThriftNodePort) }}
    nodePort: {{ .Values.agent.service.zipkinThriftNodePort }}
{{- end }}
```
_(similar code for compact, binary and sampling ports)_
