### ISSUE TITLE
esIndexCleaner not working - index-prefix missing in helm chart?

### ISSUE THREAD

**Issue by ebini** [jaegertracing/helm-charts#329]
**Describe the bug**
see https://github.com/jaegertracing/jaeger/issues/3228
the helm chart sets probably something wrong with the prefix or no prefix at all.

I think this has not really been fixed. 

**To Reproduce**
1.  deploy jaeger helm chart with elastic search as storage

(note, i use an "external" ES):
```
storage:
  type: elasticsearch
  elasticsearch:
    port: "8080"
    scheme: "http"
    host: "my-kibana"
    cmdlineParams:
      es.server-urls: "http://my-kibana:8080"
      es.tls.enabled: false
      es.version: "7"
      es.index-prefix: "jaeger-my-index"
```

2. enable index cleaner:
```
esIndexCleaner:
  enabled: true
  schedule: "4 4 * * *"
  numberOfDays: 1
```

**Expected behavior**
should delete old indexes.
it lists the indexes, but don't delete anything.

get in logs:
`{"level":"info","ts":1641844868.3567104,"caller":"./main.go:99","msg":"No indices to delete"}`

**Version (please complete the following information):**
current helm chart: version: 0.52.0

**Additional context**
workaround: if i set manually the prefix with:

```
esIndexCleaner:
  extraEnv: 
    - name: INDEX_PREFIX
      value: jaeger-my-index
```

Hope this "quick" bug report is sufficient. 
Thanks in advance.

**Comment by mehta-ankit** [comment]
If there is a prefix on the index you should be passing that extra value to the helm chart to make es-index-cleaner to work , no ?
that is the reason that parameter is available to override: 
![image](https://user-images.githubusercontent.com/22157398/149354716-43d83992-14a7-4da4-8fb1-
25dca27928d3.png)

I do not use rollover and have no prefix on my indices and helm chart and es-index-cleaner works fine for me.

**Comment by mehta-ankit** [comment]
Or is the concern that people who use es-index-rollover want the `es-index-cleaner` to be smart enough to pick up the index prefix ? 🤔

**Comment by ebini** [comment]
Hi, 
just for clarification what my intension was. (but perhaps I have a misunderstanding).
i forgot the important line in my config and edited at:

i set the prefix here:
```
storage:
  elasticsearch:
    cmdlineParams:
      es.index-prefix: "jaeger-my-index"
```

so I would have expected that the environmentvariable/start parameter for 
"esIndexCleaner" would than be automatically configured.

took a while to figure out what to do to get it running.
perhaps also only an update in the documentation would be sufficient. 
(example in values.yaml and perhaps a short note in the README.md)

Thanks in advance!

**Comment by may-cDev** [comment]
I just ran into a similiar issue when trying to let the EsIndexCleaner connect to an Elasticsearch instance via TLS. 
When setting the cmdLine parameters via storage configuration or via EsIndexCleaner.cmdlineParams it did not work. 
However, when instead setting those values via EsIndexCleaner.extraEnv as you described in your workaround, it works fine. 

The storage configuration looks as follows:

```
storage:
  elasticsearch:
    cmdlineParams:
      es.tls.enabled: true
      es.tls.ca: /tls/cert.pem
```

The configuration of the extra environment parameters as follows:

```
extraEnv:
  - name: ES_TLS
    value: "true"
  - name: ES_TLS_CA
    value: /tls/cert.pem
```

I guess the problem with this is, that the template of the EsIndexCleaner does not evaluate the cmdLineParams at all. 
When comparing the EsIndexCleaner as example with the collector-deploy template, the collector template evaluates the cmdLineArguments in the following lines (if understood correctly):

```
args:
  {{- range $key, $value := .Values.collector.cmdlineParams -}}
  {{- if $value }}
  - --{{ $key }}={{ $value }}
  {{- else }}
  - --{{ $key }}
  {{- end }}
  {{- end -}}
  {{- if not .Values.ingester.enabled -}}
  {{- include "storage.cmdArgs" . | nindent 10 }}
  {{- end }}
```

However in the the EsIndexCleaner template it looks like that:

```
args:
  - {{ .Values.esIndexCleaner.numberOfDays | quote }}
  - {{ include "elasticsearch.client.url" . }}
```

I think, both of our issues would get fixed if the cmdLineArguments would be correctly evaluated in the EsIndexCleaner template, just as they are done in the collector-deploy template (and also others.)

Any opinions on that? Is there an open issue or am I on the wrong track?
