### ISSUE TITLE
Cannot deploy "all in one" mode with helm on minikube

### ISSUE THREAD

**Issue by jbtrystram** [jaegertracing/helm-charts#337]
**Describe the bug**
I am trying to deploy jaeger in the "all in one" mode on minikube. 

**To Reproduce**
1. `minikube start `
2. install jaeger as it is showed in the doc, but with an extra flag : 
```
helm install jaeger jaegertracing/jaeger --set allInOne.enabled=true    
Error: services "jaeger-query" already exists
```

**Expected behavior**
I would expect a single pod containing all the jaeger elements 

**Version (please complete the following information):**
 - OS: fefora 35 with docker
 - Jaeger version: latest available in helm charts through : https://jaegertracing.github.io/helm-charts  
 - Deployment: minikube 1.24

**What troubleshooting steps did you try?**
The default deployment : `helm install jaeger jaegertracing/jaeger  ` works fine

**Comment by jbtrystram** [comment]
Hi ! 
Sorry I just noticed your answer now. 
In the end I got it to work with the following config : 

```
provisionDataStore:
  cassandra: false
allInOne:
  enabled: true
storage:
  type: none
agent:
  enabled: false
collector:
  enabled: false
query:
  enabled: false
```

But after a couple days of experimentation I switched to the operator anyway.
