### ISSUE TITLE
[jaeger] Cannot use the aws opensearch as backend storage.

### ISSUE THREAD

**Issue by scalalang2** [jaegertracing/helm-charts#341]
**Describe the bug**
I have tried to use the AWS OpenSearch as the backend storage.
I've made a cluster of opensearch from aws console.
And then, I changed values-yaml.file as below and installed jaeger with helm chart.

```yaml
storage:
  # allowed values (cassandra, elasticsearch)
  type: elasticsearch
  elasticsearch:
    scheme: https
    host: <my-opensearch>.ap-northeast-2.es.amazonaws.com
    port: 443
    user: admin
    usePassword: false
    password: admin
    nodesWanOnly: false
    extraEnv: []
    cmdlineParams: {}
```

Once I installed jaeger with argocd.
An error occured on both `jaeger-query` and `jaeger-ingester` as below.
```
{
  "level": "fatal",
  "ts": 1645594844.3683698,
  "caller": "./main.go:65",
  "msg": "Failed to init storage factory",
  "error": "failed to create primary Elasticsearch client: health check timeout: no Elasticsearch node available",
  "stacktrace": "main.main.func1\n\t./main.go:65\ngithub.com/spf13/cobra.(*Command).execute\n\tgithub.com/spf13/cobra@v1.3.0/command.go:856\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tgithub.com/spf13/cobra@v1.3.0/command.go:974\ngithub.com/spf13/cobra.(*Command).Execute\n\tgithub.com/spf13/cobra@v1.3.0/command.go:902\nmain.main\n\t./main.go:114\nruntime.main\n\truntime/proc.go:255"
}
```

**To Reproduce**
1. Create Opensearch from AWS console.
2. changed values.yaml file.
3. execute `helm install` command.

**Expected behavior**
Expected jaeger initialized with the opensearch.

**Version (please complete the following information):**
 - OS: Docker Image
 - Jaeger version: 1.30.0
 - Deployment: AWS EKS
