### ISSUE TITLE
Add option to change port names

### ISSUE THREAD

**Issue by KarstenSiemer** [jaegertracing/helm-charts#344]
## Requirement - what kind of business use case are you trying to solve?

Hi there!
We are currently using Jaeger and want to add authentication and authorization to the UI.
We are doing this via istio service mesh and a dex/oauth2-proxy flow.

## Problem - what in Jaeger blocks you from solving the requirement?

Sadly though, istio does not recognize the jaeger-query port as http and we need to prefix the 
port name with `http` to force the selection to have rules for the traffic to apply.
The helm chart jaeger however, doesn't give an option to configure port names.

When some other protocol than http get's selected for the port, the http rules we supply
to activate the authentication flow never apply.

As a quick fix we deploy an additional service with the same selector to force selection of http, but
it would be nice if we could just configure the port name.

## Proposal - what do you suggest to solve the problem or improve the existing situation?
```
query:
  service:
    annotations: {}
    type: ClusterIP
    # List of IP ranges that are allowed to access the load balancer (if supported)
    loadBalancerSourceRanges: []
    port: 80
    # Specify a custom port name
    portName: query
    # Specify a custom target port (e.g. port of auth proxy)
    # targetPort: 8080
    # Specify a specific node port when type is NodePort
    # nodePort: 32500
```
I'd like to give the service sections an interface to configure the port names via a `name` field.
The default value should be is currently hardcoded. Folks that use istio or something else can then just insert whatever they desire. Like `query.service.portName: http-query`

For us doing it on the query service would suffice, but we should follow through and make the name configurable on all services.
e.g agent:

```
  service:
    annotations: {}
    # List of IP ranges that are allowed to access the load balancer (if supported)
    loadBalancerSourceRanges: []
    type: ClusterIP
    # zipkinThriftPort :accept zipkin.thrift over compact thrift protocol
    zipkinThrift:
      name: zipkin-compact
      port: 5775
    # compactPort: accept jaeger.thrift over compact thrift protocol
    compact:
      name: jaeger-compact
      port: 6831
    # binaryPort: accept jaeger.thrift over binary thrift protocol
    binary:
      name: jaeger-binary
      port: 6832
    # samplingPort: (HTTP) serve configs, sampling strategies
    sampling:
      name: http
      port: 5778
```

## Any open questions to address

* We could also make this easier to configure by adding an istio options field and activate port naming convention and auto configure correct prefixes in this chart.
* Another idea is to just hardcode istio portnaming convention, as the port names don't hurt people who are not using istio

Or we add maps for port options
```
query:
  service:
    annotations: {}
    type: ClusterIP
    # List of IP ranges that are allowed to access the load balancer (if supported)
    loadBalancerSourceRanges: []
    port: 
      name: query
      number: 80
    # Specify a custom target port (e.g. port of auth proxy)
    # targetPort: 8080
    # Specify a specific node port when type is NodePort
    # nodePort: 32500
```

If this feature request is accepted, I'd be happy to contribute a PR.
Thanks for the consideration
