### ISSUE TITLE
URGENT! Jaeger-collector logs the following error:  failed to receive the preface from client

### ISSUE THREAD

**Issue by LPinto98** [jaegertracing/helm-charts#364]
I had previously installed the jaeger helm charts in kubernetes cluster (cluster A) at the start of Dec 2021, the traces were collected by opentelemetry collector in a different cluster (cluster B) and then sent to the jaeger-collector. This configuration was a success and we retried afterwards the same configuration at the start of February, and it was working then as well. But as of April, when I tried installing the same configuration on another cluster, I get the following logs in my jaeger-collector: 

```
{"level":"info","ts":1651173715.1693428,"caller":"flags/service.go:117","msg":"Mounting metrics handler on admin server","route":"/metrics"}
{"level":"info","ts":1651173715.1694136,"caller":"flags/service.go:123","msg":"Mounting expvar handler on admin server","route":"/debug/vars"}
{"level":"info","ts":1651173715.1697037,"caller":"flags/admin.go:104","msg":"Mounting health check on admin server","route":"/"}
{"level":"info","ts":1651173715.1697567,"caller":"flags/admin.go:115","msg":"Starting admin HTTP server","http-addr":":14269"}
{"level":"info","ts":1651173715.1697779,"caller":"flags/admin.go:96","msg":"Admin server started","http.host-port":"[::]:14269","health-status":"unavailable"}
{"level":"info","ts":1651173715.5672677,"caller":"cassandra/factory.go:110","msg":"Cassandra archive storage configuration is empty, skipping"}
{"level":"info","ts":1651173715.650385,"caller":"static/strategy_store.go:203","msg":"No sampling strategies provided or URL is unavailable, using defaults"}
{"level":"info","ts":1651173715.673714,"caller":"server/grpc.go:90","msg":"Starting jaeger-collector gRPC server","grpc.host-port":":14250"}
{"level":"info","ts":1651173715.6738496,"caller":"server/http.go:48","msg":"Starting jaeger-collector HTTP server","http host-port":":14268"}
{"level":"info","ts":1651173715.674199,"caller":"server/zipkin.go:49","msg":"Not listening for Zipkin HTTP traffic, port not configured"}
{"level":"info","ts":1651173715.674468,"caller":"healthcheck/handler.go:129","msg":"Health Check state change","status":"ready"}
{"level":"warn","ts":1651204786.8182864,"caller":"channelz/logging.go:62","msg":"[core]grpc: Server.Serve failed to create ServerTransport: connection error: desc = \"transport: http2Server.HandleStreams failed to receive the preface from client: read tcp 172.30.225.85:14250->10.163.1.142:54370: read: connection reset by peer\"","system":"grpc","grpc_log":true}
{"level":"warn","ts":1651422851.6086707,"caller":"channelz/logging.go:62","msg":"[core]grpc: Server.Serve failed to create ServerTransport: connection error: desc = \"transport: http2Server.HandleStreams failed to receive the preface from client: read tcp 172.30.225.85:14250->10.163.1.142:57296: read: connection reset by peer\"","system":"grpc","grpc_log":true}
{"level":"info","ts":1651649254.383259,"caller":"grpclog/component.go:71","msg":"[transport]transport: loopyWriter.run returning. connection error: desc = \"transport is closing\"","system":"grpc","grpc_log":true}
{"level":"warn","ts":1651650855.9066455,"caller":"channelz/logging.go:62","msg":"[core]grpc: Server.Serve failed to create ServerTransport: connection error: desc = \"transport: http2Server.HandleStreams failed to receive the preface from client: read tcp 172.30.225.85:14250->10.163.1.142:55954: read: connection reset by peer\"","system":"grpc","grpc_log":true}
```

These are the steps I followed: 

In cluster A,
1. Install jaeger using helm charts
`helm repo add jaegertracing https://jaegertracing.github.io/helm-charts`
`helm install jaeger jaegertracing/jaeger`

2. Expose the jaeger-collector endpoint using loadbalancer:
```
apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector-lb
  namespace: default
  annotations:
    service.kubernetes.io/ibm-load-balancer-type: "external" # nlb
    service.kubernetes.io/ibm-load-balancer-nlb-target-type: "ip"
    service.kubernetes.io/ibm-load-balancer-scheme: internet-facing
spec:
  ports:
    - name: grpc
      port: 14250
      protocol: TCP
      targetPort: 14250
    - name: http
      port: 14268
      protocol: TCP
      targetPort: 14268
    - name: otlp
      port: 4317
      protocol: TCP
      targetPort: 4317
  type: LoadBalancer
  selector:
    app.kubernetes.io/component: collector
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/name: jaeger

```
3. Expose the jaeger-query endpoint using the command:
`  kubectl expose deployment jaeger-query --type=LoadBalancer --name=jaeger-query-lb --port=16686`

In cluster B,
1. Deploy the application to be traced
2. Ensure cert-manager is installed, if not, use the command:  `kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.6.1/cert-manager.yaml`
3. Deploy Opentelemetry operator : 
```kubectl apply -f https://github.com/open-telemetry/opentelemetry-operator/releases/latest/download/opentelemetry-operator.yaml```
4. Deploy Standalone otel-collector:
```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: simplest
spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      batch: {} 
      batch/2: 
        timeout: 10s
        send_batch_size: 10000    
    exporters:
      logging:
      jaeger:
        endpoint: 169.38.89.235:14250
        timeout: 30s
        tls: 
          insecure: true
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [jaeger, logging]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [jaeger,logging]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [jaeger, logging]
```
5. Expose simplest-collector deployment using loadbalancer (otel-collector-lb.yaml): `kubectl apply -f otel-collector-lb.yaml`
6. Update sidecar instrumentation yaml, with the endpoint of otel-collector-lb as exporter: `kubectl apply -f sidecar.yaml`
```
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: my-instrumentation
  annotations: 
    instrumentation.opentelemetry.io/inject-java: "true"
    instrumentation.opentelemetry.io/inject-nodejs: "true"
    instrumentation.opentelemetry.io/inject-python: "true"
spec:
  exporter:
    endpoint: http://169.38.x.x:4317
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "0.25"
  java:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:latest
  nodejs:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:latest
  python:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:latest
``` 
7. Annotate the namespace using:
`kubectl annotate namespace default instrumentation.opentelemetry.io/inject-python=true` 
`kubectl annotate namespace default instrumentation.opentelemetry.io/inject-java=true`
`kubectl annotate namespace default instrumentation.opentelemetry.io/inject-nodejs=true`

8. Patch the microservice deployments using the following command:  
```
kubectl patch deployment.apps/<DEPLOYMENT_NAME> -p '{"spec": {"template": {"metadata": {"annotations": {"[sidecar.opentelemetry.io/inject](http://sidecar.opentelemetry.io/inject)": "true"}}}}}'
```
