### ISSUE TITLE
Disabling certs creation in v2.32.2 helm chart breaks the jaeger deployment

### ISSUE THREAD

**Issue by AshutoshNirkhe** [jaegertracing/helm-charts#375]
**Describe the bug**
v2.32.x seems to be introducing admission webhooks and associated certificates. But if I want to disable them all, its not possible to do so as per https://github.com/jaegertracing/helm-charts/blob/jaeger-operator-2.32.2/charts/jaeger-operator/templates/deployment.yaml#L52

Are they mandatory going forward ? 
Ref - https://www.jaegertracing.io/docs/1.35/operator/#prerequisite 

**To Reproduce**
1. Disable webhooks and certificates via values.yaml
```
certs:
  certificate:
    create: false
  issuer:
    create: false
webhooks:
  mutatingWebhook:
    create: false
  service:
    create: false
  validatingWebhook:
    create: false
```

2. Try to upgrade jaeger helm chart from 2.27.0 to 2.32.2

3. Pod will stay in Waiting/ContainerCreating state forever and will show below message if we do kubectl describe on pod,

```
  Warning  FailedMount  50s (x10 over 5m)    kubelet            MountVolume.SetUp failed for volume "cert" : secret "jaeger-operator-service-cert" not found
  Warning  FailedMount  42s (x2 over 2m57s)  kubelet            Unable to attach or mount volumes: unmounted volumes=[cert], unattached volumes=[cert kube-api-access-7bkf8]: timed out waiting for the condition

```
**Expected behavior**
Currently deployment.yaml tries to load volume from certificate secret even if we disable cert creation. It needs to have the condition to check for that flag before volume/volume mount creation. That way, webhooks/certificates creation won't be a mandatory configuration.

**Screenshots**

**Version (please complete the following information):**
 - OS: Linux Ubuntu
 - Jaeger version: 1.34.1
 - Deployment: Kubernetes v1.22

**What troubleshooting steps did you try?**
Try to follow https://www.jaegertracing.io/docs/latest/troubleshooting/ and describe how far you were able to progress and/or which steps did not work.

**Additional context**

**Comment by rotarur** [comment]
is there an ETA for this bug fix? We're facing the same issue

**Comment by mjnagel** [comment]
> There should be a way to disable creating the certificates and to provider the names of the relevant secrets created before running the `jaeger-operator` Helm chart.

@avishefi This is possible, reference the below values:

```yaml
certs:
  issuer:
    create: false # defaults to true, but you can disable the chart creation of the issuer
    name: "" # leave empty
  certificate:
    create: false # defaults to true but you can disable the chart creation of the cert
    namespace: "jaeger" # namespace for the secret
    secretName: "my-secret" # secret with the cert
```

The other thing you may need depending on how you create the certs would be the `clientConfig.caBundle` value set in the webhook spec - which isn't currently exposed in values. I use the [webhook cert gen](https://github.com/kubernetes/ingress-nginx/tree/main/images/kube-webhook-certgen) to dynamically generate these certs and then patch the webhooks. I think if you make use of cert-manager this will all be handled for you via the annotations.
