### ISSUE TITLE
[Bug]: jaeger-query already exists

### ISSUE THREAD

**Issue by githubcdr** [jaegertracing/helm-charts#388]
### What happened?

Helm install/upgrade does not work with allInOne enabled;

```
provisionDataStore:
  cassandra: false
  elasticsearch: false
  kafka: false

allInOne:
  enabled: true
```

### Steps to reproduce

1. Install with helm

```
helm -n jaeger install jaeger jaegertracing/jaeger --values values.yaml
```

### Expected behavior

Working install and setup

### Relevant log output

```shell
Error: INSTALLATION FAILED: services "jaeger-query" already exists
```

**Comment by jplayout** [comment]
You have to set to false the others pods normally installed with the operator : 
```
provisionDataStore:
  cassandra: false
allInOne:
  enabled: true
agent:
  enabled: false
collector:
  enabled: false
query:
  enabled: false
```
