### ISSUE TITLE
[Feature]: add support for "Service Performance Monitoring (SPM)" 

### ISSUE THREAD

**Issue by maozza** [jaegertracing/helm-charts#440]
### Requirement

I want to enable  Service Performance Monitoring (SPM) feature with helm installation
install procedure:

```
helm repo add jaegertracing https://jaegertracing.github.io/helm-charts
helm upgrade --install jaeger jaegertracing/jaeger  --values custom-values.yaml
```

### Problem

will it be possible to add support for Service Performance Monitoring (SPM) in the helm chart?
more info  can be found here -> https://www.jaegertracing.io/docs/1.41/spm/

**Comment by maozza** [comment]
I was trying to add the following values, and I can see that Prometheus scrapes the metrics from the controller and query, but the monitor is still not showing any metrics.
```
query:
  extraEnv:
  - name: METRICS_STORAGE_TYPE
    value: prometheus
  - name: PROMETHEUS_SERVER_URL
    value: prometheus-kube-prometheus-prometheus.monitoring:9090
  serviceMonitor:
    enabled: true
    additionalLabels:
     release: prometheus
collector:
  serviceMonitor:
    enabled: true
    additionalLabels:
     release: prometheus
```
