### ISSUE TITLE
[Feature]: Support InitContainer in collector

### ISSUE THREAD

**Issue by pie-r** [jaegertracing/helm-charts#452]
### Requirement

Jaeger Operator doesn't support yet Elasticsearch 8, for this reason users have to 

```
   storage:
      type: elasticsearch
      secretName: ${elasticsearch_credentials_secret}
      options:
        es:
          server-urls: http://${elasticsearch_url}
          max-span-age: ${elasticsearch_retention * 24}h
          version: 7                                                 # Necessary as it doesn't work with 8 yet
          create-index-templates: false               # Necessary as it doesn't work with 8 yet
```

The index-tempalte could be added as `initContainer` to the collector manifest.

Reference: https://github.com/jaegertracing/jaeger/issues/3571

### Problem

Jaeger doesn't support yet Elasticsearch 8.x

### Proposal

Add an InitContainter section in the elasticsearch collector manifest
