### ISSUE TITLE
[Feature]: It's not possible to use Cassandra without authorization.

### ISSUE THREAD

**Issue by avbit** [jaegertracing/helm-charts#460]
### Requirement

use Cassandra without authorization.

### Problem

It's not possible to use Cassandra without authorization.

### Proposal

modify  file `charts/jaeger/templates/_helpers.tpl`... append condition `.Values.storage.cassandra.usePassword`:
```
{{- if .Values.storage.cassandra.usePassword }}
- name: CASSANDRA_USERNAME
  value: {{ .Values.storage.cassandra.user }}
- name: CASSANDRA_PASSWORD
  valueFrom:
    secretKeyRef:
      name: {{ if .Values.storage.cassandra.existingSecret }}{{ .Values.storage.cassandra.existingSecret }}{{- else }}{{ include "jaeger.fullname" . }}-cassandra{{- end }}
      key: password
{{- end }}
```

I can't make a pull request due to lack of rights ((
