### ISSUE TITLE
[Feature]: Add possibility to specify defaultMode in extraConfigmapMounts

### ISSUE THREAD

**Issue by pavel-luhin** [jaegertracing/helm-charts#461]
### Requirement

As a jaeger helm chart user, I want to pass initial elasticsearch index templates script via configmap.

### Problem

Jaeger helm chart does not allow me to specify `defaultMode: 0744` to make my script from configMap executable.

### Proposal

Add possibility to specify `defaultMode` in `extraConfigmapMounts`, to make it look like this:
```
    extraConfigmapMounts:
      - name: init-script
        mountPath: /opt/script.sh
        subPath: jaeger-elastic-index-templates.sh
        readOnly: true
        configMap: configmap-jaeger-elasticsearch-init-script
        defaultMode: 0744
```
