### ISSUE TITLE
[jaeger] 0.19.3 release breaks ability to specify ElasticSearch url 

### ISSUE THREAD

**Issue by sdague** [jaegertracing/helm-charts#48]
The 0.19.3 release includes changes to the template for setting the elastic search url if using an existing elastic search and not provisioning. It works in 0.18.3 and 0.19.2. 

Reproduce:

Set a values file with:

```yaml
  provisionDataStore:
    cassandra: false
    elasticsearch: false
  storage:
    type: elasticsearch
    elasticsearch:
      scheme: https
      host: somehost
      user: someuser
      port: 9000
      existingSecret: jaeger-secrets
      usePassword: true
```

Run `helm template jaeger -f values.yaml` and you'll see that the `ES_SERVER_URLS` will not have a value set.
