### ISSUE TITLE
[Bug]:  all-in-one helm install only support memory storage?

### ISSUE THREAD

**Issue by njfanxun** [jaegertracing/helm-charts#485]
### What happened?

in the helm-charts jaeger templates allinone-deplaoy.yaml
```yaml
spec:
      containers:
        - env:
          {{- if .Values.allInOne.extraEnv }}
            {{- toYaml .Values.allInOne.extraEnv | nindent 12 }}
          {{- end }}
            - name: SPAN_STORAGE_TYPE
              value: memory
            - name: COLLECTOR_ZIPKIN_HOST_PORT
              value: :9411
            - name: JAEGER_DISABLED
              value: "false"
            - name: COLLECTOR_OTLP_ENABLED
              value: "true"
            {{- if .Values.allInOne.samplingConfig }}
            - name: SAMPLING_STRATEGIES_FILE
              value: /etc/conf/strategies.json
            {{- end }}
        {{- with .Values.allInOne.envFrom }}
          envFrom: {{- toYaml . | nindent 12 }}
        {{- end }}
```
so，custom env from extraEnv will be covered.
how to set SPAN_STORAGE_TYPE = cassandra?
It will always be on top of the environment variable "memory".

### Steps to reproduce

set helm values.yaml

### Expected behavior

helm install all-in-one
