### ISSUE TITLE
[Feature]: Add initContainers for query-deploy.yaml

### ISSUE THREAD

**Issue by vscoder-ht** [jaegertracing/helm-charts#512]
### Requirement

We use clickhouse as storage backend for traces. But thos possibility is available only for jaeger-operator CR kind: Jaeger https://github.com/jaegertracing/jaeger-clickhouse/blob/main/guide-kubernetes.md
We need to deploy jaeger-query standalone without other components, but it is impossible in jaeger-operator.

### Problem

jaeger helm chart allows to deploy jaeger-query standalone.

I trying to configure jaeger-clickhouse plugin for jaeger-query. I can add

```yaml
query:
  cmdlineParams:
    - '--grpc-storage-plugin.binary=/plugin/jaeger-clickhouse'
    - >-
      --grpc-storage-plugin.configuration-file=/plugin-config/config.yaml
    - '--grpc-storage-plugin.log-level=debug'
  extraSecretMounts:
    - name: plugin-config
      mountPath: /plugin-config
      readOnly: true
      secretName: jaeger-clickhouse-secret
```

But I can't to add initContainer to jaeger-query because there isn't such block in `query-deploy.yaml`

### Open questions

Could you please add block to `query-deploy.yaml` like in `collector-deploy.yaml`?

```yaml
    spec:
      ...
      {{- if .Values.query.initContainers }}
      initContainers:
        {{- toYaml .Values.query.initContainers | nindent 8 }}
      {{- end}}
```
