### ISSUE TITLE
[Bug]: tls.enabled value is bound with hardcoded values

### ISSUE THREAD

**Issue by puffitos** [jaegertracing/helm-charts#513]
### What happened?

Hopefully this isn't a "No one gets TLS".

I just wanted to deploy jaeger with an elasticsearch statefulset deployed via the ECK operator. The ECK operator rolls out its own certificates, which is fine. 

When I activate TLS via the normal helm chart (`tls.enable` is set to true), the ES_TLS_CA variable is set to a default, hardcoded value, which is per default pumped into the environment of all relevant containers (`collector` and `query`). A secret with a specific name must be created, which contains the `ca-cert.pem` file. This already makes the chart **non-deployable**, without creating said secret, which doesn't seem directly possible via the ECK operator. As certificates are rotated via ECK, creating a manual secret by collecting the needed data seemed counter-intuitive.

Given that the elasticsearch deployment doesn't create one single secret with the expected value with certificate chain (`/es-tls/ca-cert.pem`), I found no simple way to mount the the certs and key created via the Elasticsearch deployment. An `elastisearch` resource creates a secret containing 3 values, ca.crt, tls.key and tls.crt. That secret cannot be mounted via the current chart in a way, which wouldn't block the deployemt of jaeger. 

Using `additionalSecretMounts` doesn't work, as we must activate tls, to be able to be able to use the `es.tls.ca`, `es.tls.cert` and `es.tls.key` flags.  

### Steps to reproduce

First create a simple `elasticsearch` resource via the ECK operator:

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
    count: 1
    name: default
  version: 7.17.13
```

The deploy jaeger with the following values:

```yaml
provisionDataStore:
  cassandra: false
  elasticsearch: false

storage:
  type: elasticsearch
  elasticsearch:
    port: 9200
    scheme: https
    user: elastic
    indexPrefix: test
    host: quickstart-es-internal-http.tracing.svc
    usePassword: false
    tls:
      enabled: true
      secretName: quickstart-es-http-certs-internal

agent:
  enabled: true

collector:
  enabled: true
  extraEnv:
    - name: ES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: quickstart-es-elastic-user
          key: elastic
query:
  enabled: true
  extraEnv:
    - name: ES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: quickstart-es-elastic-user
          key: elastic
```

The collector and query containers cannot start, as they cannot find the expected default secret in the default directory, which is defined via the `ES_TLS_CA` via the `elasticsearch.env` helper function. The secrets are mounted per default in all related containers via:

```yaml
              - name: {{ .Values.storage.elasticsearch.tls.secretName }}
                mountPath: "/es-tls/ca-cert.pem"
                subPath: "ca-cert.pem"
```

But the secret created via the ECK Operator has the following syntax:

```yaml
ca.crt: |
  -----BEGIN CERTIFICATE-----
  xxxx
  -----END CERTIFICATE-----
tls.crt: |
  -----BEGIN CERTIFICATE-----
  xxxx  
  -----END CERTIFICATE-----
  -----BEGIN CERTIFICATE-----
  xxxx
  -----END CERTIFICATE-----
```

The collector and query are getting EOF errors / other related errors when trying to connect to the Elasticsearch instance.

### Expected behavior

One should be able to mount a secret with multiple files and then use those files by using either `cmdlineParams` or the environment variables `ES_TLS_XXX`.

One must activate tls.enabled before doing that though, which creates hardcoded mounts and variables.

### Additional context

I'll try and replicate the error to produce logs again. I've created a fork where the hard-coded values are replaced by variables, so the chart may become more flexible.

### Jaeger backend version

1.45.0

### Stogage backend

Elasticsearch 7.x.x

### Operating system

Linux
