### ISSUE TITLE
[Bug]: jaeger-chart: does not exist .Values.storage.elasticsearch.tls in es-rollover-hook.yml

### ISSUE THREAD

**Issue by obervinov** [jaegertracing/helm-charts#521]
### What happened?

**Description**
[es-rollover-hook.yml](https://github.com/jaegertracing/helm-charts/blob/main/charts/jaeger/templates/es-rollover-hook.yml#L85-L89) template does not support the `.Values.storage.elasticsearch.tls` settings, as implemented for example in [es-rollover-cronjob.yaml](https://github.com/jaegertracing/helm-charts/blob/main/charts/jaeger/templates/es-rollover-cronjob.yaml#L108-L112).

This creates a situation where `rollover-hook-init` cannot be used with a custom CA configured via parameters `storage.elasticsearch.tls`, as it will fall with an error of the missing certificate installed in [ES_TLS_CA](https://github.com/jaegertracing/helm-charts/blob/main/charts/jaeger/templates/_helpers.tpl#L367-L368).

If you try to use parameter `.Values.esRollover.extraSecretMounts`, it causes a conflict with the environment variable [ES_TLS_CA](https://github.com/jaegertracing/helm-charts/blob/main/charts/jaeger/templates/_helpers.tpl#L367-L368).

The only option left is not to use parameter `.Values.storage.elasticsearch.tls`,  but to manually declare `extraSecrets` and `extraEnvs` for each chart microservice.

I would like to correct this situation with a small edit.

### Steps to reproduce

1. Set these values for the jaeger chart
```yaml
storage:
  type: elasticsearch
  elasticsearch:
    scheme: https
    host: es-node-1.example.com
    tls:
      enabled: true
      secretName: intermidiate-ca-certificate

esRollover:
  enabled: true
  extraEnv:
    - name: CONDITIONS
      value: '{"max_age": "1d"}'
  schedule: "40 14 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
```
2. Install this helm chart
3. Get an error

### Expected behavior

The `.Value.storage.elasticsearch.tls` parameter automatically adds the mounting of the specified `Secret` to the executed [es-rollover-hook.yml](https://github.com/jaegertracing/helm-charts/blob/main/charts/jaeger/templates/es-rollover-hook.yml) just as in the template [es-rollover-cronjob.yaml](https://github.com/jaegertracing/helm-charts/blob/main/charts/jaeger/templates/es-rollover-cronjob.yaml#L108-L112)

### Relevant log output

```shell
Error: failed to load CA CertPool: failed to load CA /es-tls/ca-cert.pem: open /es-tls/ca-cert.pem: no such file or directory
```

### Screenshot

<img width="1503" alt="Снимок экрана 2023-11-15 в 17 32 18" src="https://github.com/jaegertracing/helm-charts/assets/49606362/5df5962e-74b0-46cf-b2f0-7e2027105e62">
<img width="1406" alt="Снимок экрана 2023-11-15 в 17 36 27" src="https://github.com/jaegertracing/helm-charts/assets/49606362/f808c062-997f-4d74-bf85-57f71b950dca">

### Jaeger backend version

v1.43

### Stogage backend

Elasticsearch

### Operating system

Linux

### Deployment model

Kubernetes
