### ISSUE TITLE
[Bug]: jaeger chart incompatible with recent bitnami charts

### ISSUE THREAD

**Issue by rquinio1A** [jaegertracing/helm-charts#528]
### What happened?

The jaeger chart depends on an old version of the bitnami common sub-chart: https://github.com/jaegertracing/helm-charts/blob/main/charts/jaeger/Chart.yaml#L42

Due to the way helm handles named templates globally (https://github.com/helm/helm/issues/11561), this means bitnami common sub-chart version must be updated quite frequently to avoid incompatibilities when multiple charts are part of the same umbrella chart: https://github.com/bitnami/charts/issues/20570 

### Steps to reproduce

Use a recent version of a bitnami chart (ex: mongodb > 13.16.0) in the same umbrella chart as jaeger:

```
apiVersion: v2
name: umbrella-chart
type: application
version: 1.0.0
dependencies:
- name: mongodb
  version: ~13.18.0
  repository: oci://registry-1.docker.io/bitnamicharts
- name: jaeger
  version: ~0.73.0
  repository: https://jaegertracing.github.io/helm-charts
```

With helm v3.13.1:

```
$ helm template .
Error: template: umbrella-chart/charts/mongodb/templates/standalone/svc.yaml:12:14: executing "umbrella-chart/charts/mongodb/templates/standalone/svc.yaml" at <include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $)>: error calling include: template: umbrella-chart/charts/jaeger/charts/common/templates/_labels.tpl:6:27: executing "common.labels.standard" at <include "common.names.name" .>: error calling include: template: umbrella-chart/charts/jaeger/charts/common/templates/_names.tpl:6:18: executing "common.names.name" at <.Chart.Name>: nil pointer evaluating interface {}.Name
```

### Expected behavior

jaeger chart should be compatible with latest bitnami chart, or not depend on bitnami common sub-chart.
