### ISSUE TITLE
[Bug]: Helm Install with Elasticsearch fails due to missing directory

### ISSUE THREAD

**Issue by tech1ndex** [jaegertracing/helm-charts#584]
### What happened?

Trying to move to version 3.x.x of this chart with Elasticsearch and it appears as if a new Init Container named `copy-default-plugins` is being added which is causing ES to fail to start with 
```
+ jaeger-elasticsearch-master-0 › copy-default-plugins
+ jaeger-elasticsearch-master-0 › sysctl
jaeger-elasticsearch-master-0 copy-default-plugins /bin/bash: line 2: /opt/bitnami/scripts/libfs.sh: No such file or directory
- jaeger-elasticsearch-master-0 › copy-default-plugins
- jaeger-elasticsearch-master-0 › sysctl
```

### Steps to reproduce

1. Install Jaeger chart version 3.0.0 or higher with the following values:

```
  values:
    provisionDataStore:
      cassandra: false
      elasticsearch: true
    storage:
      type: elasticsearch
```

### Expected behavior

I expect Elasticsearch pods to come up in a healthy state.
