### ISSUE TITLE
[Feature]: Ability to edit edit port name in service for collector and query.

### ISSUE THREAD

**Issue by vishukamble** [jaegertracing/helm-charts#589]
### Requirement

I want the ability to change the port name in spec.ports.name for the Jaeger services ([query ](https://github.com/jaegertracing/helm-charts/blob/main/charts/jaeger/templates/query-svc.yaml#L26-L29) and [collector](https://github.com/jaegertracing/helm-charts/blob/main/charts/jaeger/templates/collector-svc.yaml#L63-L65)). This is to allow for custom port names such as http-admin or other names which help enforce HTTPS via Istio. Renaming the port with the prefix http allows Istio to automatically apply mTLS, providing HTTPS for service monitoring.

### Problem

I am trying to enable mTLS for service monitors with Prometheus using Istio. The current Jaeger Helm chart does not allow changing the port name in the service monitor configuration, which prevents me from enforcing HTTPS.

I had to manually create service monitors and disable the ones provided by the Helm chart as they don't allow specifying tlsConfig for the Jaeger query and collector service monitors. Here are the links to the current implementations:

[Jaeger query service monitor](https://github.com/jaegertracing/helm-charts/blob/main/charts/jaeger/templates/query-servicemonitor.yaml#L21)
[Jaeger collector service monitor](https://github.com/jaegertracing/helm-charts/blob/main/charts/jaeger/templates/collector-servicemonitor.yaml#L63)

My current service monitor specification looks like this:
```
spec:
  endpoints:
  - path: /metrics
    port: http-admin
    scheme: https
    tlsConfig:
      caFile: /etc/prom-certs/root-cert.pem
      certFile: /etc/prom-certs/cert-chain.pem
      insecureSkipVerify: true
      keyFile: /etc/prom-certs/key.pem
```
The problem arises with the port name. Using the default port name admin results in an unexpected EOF error. However, if I manually change the port name to http-admin in both the service monitor and the service definitions for the Jaeger query and collector, it works correctly with Istio enforcing HTTPS.

### Proposal

Query Service:
```
  - name: {{ .Values.service.portName | default "admin" }}
    port: 16687
    protocol: TCP
    targetPort: {{ .Values.service.targetPortName | default "admin" }}
```

Collector Service:
```
   - name: {{ .Values.service.portName | default "admin" }}
    port: 14269
    targetPort: {{ .Values.service.targetPortName | default "admin" }}
```
