### ISSUE TITLE
[jaeger-operator] Bug: Volume mount name longer than 63 char

### ISSUE THREAD

**Issue by faheem-nadeem** [jaegertracing/helm-charts#59]
Hi,

Not sure if this is the correct place to file this issue but here it goes.

Trying the operator chart with a minimal values file. I enabled jaeger instance creation with the operator installation without providing any specs.

Chart Version: 2.13.1
Operator Version: 1.16.0
Helm version: v2.16.3

```
crd:
  install: true
jaeger:
  # Specifies whether Jaeger instance should be created
  create: true
  spec: {}

rbac:
  # Specifies whether RBAC resources should be created
  create: true
  pspEnabled: false
  clusterRole: true

serviceAccount:
  # Specifies whether a ServiceAccount should be created
  create: true
  # The name of the ServiceAccount to use.
  # If not set and create is true, a name is generated using the fullname template
  name:
```

Leads to the following errors.

```
 time="2020-02-27T15:50:45Z" level=info msg=Versions arch=amd64 identity=jaegertracing.jaegertracing-jaeger-operator jaeger=1.16.0 jaeger-operator=v1.16.0 operator-sdk=v0.12.0 │
│  os=linux version=go1.13.3                                                                                                                                                     │
│ time="2020-02-27T15:50:47Z" level=info msg="Auto-detected the platform" platform=kubernetes                                                                                    │
│ time="2020-02-27T15:50:47Z" level=info msg="Automatically adjusted the 'es-provision' flag" es-provision=no                                                                    │
│ time="2020-02-27T15:50:47Z" level=info msg="Automatically adjusted the 'kafka-provision' flag" kafka-provision=no                                                              │
│ time="2020-02-27T15:50:47Z" level=info msg="The service account running this operator does not have the role 'system:auth-delegator', consider granting it for additional capa │
│ bilities"                                                                                                                                                                      │
│ time="2020-02-27T15:50:50Z" level=info msg="Storage type not provided. Falling back to 'memory'" instance=jaegertracing-jaeger-operator-jaeger namespace=jaegertracing         │
│ time="2020-02-27T15:50:51Z" level=error msg="failed to apply the changes" error="Deployment.apps \"jaegertracing-jaeger-operator-jaeger\" is invalid: [spec.template.spec.volu │
│ mes[0].name: Invalid value: \"jaegertracing-jaeger-operator-jaeger-sampling-configuration-volume\": must be no more than 63 characters, spec.template.spec.containers[0].volum │
│ eMounts[0].name: Not found: \"jaegertracing-jaeger-operator-jaeger-sampling-configuration-volume\"]" execution="2020-02-27 15:50:50.576488163 +0000 UTC" instance=jaegertracin │
│ g-jaeger-operator-jaeger namespace=jaegertracing```
