### ISSUE TITLE
[jaeger v2] Helm Chart

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/helm-charts#610]
Part of LFX Mentorship 2024 Term 3 https://github.com/jaegertracing/jaeger/issues/5772.

## Background
Jaeger is an open-source, end-to-end distributed tracing system that helps monitor and troubleshoot transactions in complex, microservices-based environments. Jaeger v2 is a major new version where we rebase all Jaeger backend components (agent, collector, ingester, and query) on top of the OpenTelemetry Collector, bringing significant improvements and changes to the platform. Helm is a package manager for Kubernetes that simplifies the deployment and management of applications.

Currently, Jaeger v1 has an [official Helm chart](https://github.com/jaegertracing/helm-charts), but there isn't one yet for Jaeger v2.

Relevant links:
- Jaeger: https://www.jaegertracing.io/
- Getting started: https://www.jaegertracing.io/mentorship-for-mentees/
- [Jaeger v2 RFC](https://docs.google.com/document/d/1s4_6VgAS7qAVp6iEm5KYvpiGw3h2Ja5T5HpKo29iv00/edit#)
- Helm: https://helm.sh/
- Existing Jaeger Helm charts: https://github.com/jaegertracing/helm-charts

## Project Objective
The goal of this project is to develop a comprehensive Helm chart for Jaeger v2 that allows for easy deployment and management of Jaeger v2 components in Kubernetes environments. This chart should provide flexibility in configuration, support various deployment scenarios, and integrate well with the new architecture of Jaeger v2.

## Key Features and Implementation

1. **Jaeger v2 Component Deployment**
   - Create Helm templates for all existing Jaeger v1 deployment strategies
   - Ensure proper sequencing of component deployment.
   - Implement support for different Jaeger v2 deployment strategies.

2. **Storage Backend Configuration**
   - Implement support for existing storage backends (Elasticsearch, Cassandra)
   - Include options for deploying these backends as part of the Helm chart or connecting to existing instances.

3. **Security Features**
   - Implement TLS support for secure communication between components.
   - Include RBAC resources for secure deployment in Kubernetes clusters.
   - Provide options for setting up authentication and authorization.

4. **Resource Management**
   - Implement resource requests and limits for all deployed components.
   - Provide options for fine-tuning resource allocation based on deployment size and requirements.

5. **Configurability and Customization**
   - Design an approach that allows users to easily customize their Jaeger v2 deployment.

6. **Documentation and Examples**
   - Create comprehensive documentation for the Helm chart, including installation, configuration, and usage guidelines.
   - Develop a set of example values files for common deployment scenarios.

## Expected Outcome
By the end of this project, we aim to have a production-ready Helm chart for Jaeger v2 that is:
- Fully functional and tested on the current version of Kubernetes
- Well-documented with clear usage instructions and examples
- Flexible enough to support a wide range of deployment scenarios
- Ready for submission to the official Jaeger Helm chart repository

**Comment by yurishkuro** [comment]
I think the first thing we need to do before extending v2 chart capabilities is to productionalize it. Iirc one had to sync the separate branch locally, only then the chart was usable. That's neither user friendly nor official way of using a chart. We need a solution where a typical Helm process can be used. Does it mean we need to move this branch into a subdirectory of the main branch?

**Comment by AfrouzMashayekhi** [comment]
> I think the first thing we need to do before extending v2 chart capabilities is to productionalize it. Iirc one had to sync the separate branch locally, only then the chart was usable. That's neither user friendly nor official way of using a chart. We need a solution where a typical Helm process can be used. Does it mean we need to move this branch into a subdirectory of the main branch?

yes I think having a subdirectory is more user friendly.

**Comment by yurishkuro** [comment]
Well but naming it v2 is quite misleading since the chart has its own versioning scheme. Ideally the v2 flavor should become the primary content of the chart. I don't know what is the best way to make the two flavors to co-exist, and I don't have time to research it, while the maintainers of the existing chart did not provide any suggestions.

**Comment by sergeykad** [comment]
The current Helm chart is 3.x and supports Jaeger 1.x
IMHO adding Helm chart 4.x with support for Jaeger 2.x will work fine. 

I am not sure how it should be maintained in parallel, but at least currently they release both Jaeger 1.x and Jaeger 2.x [simultaneously](https://github.com/jaegertracing/jaeger/releases). So maybe a separate directory for each chart?

**Comment by yurishkuro** [comment]
But the bigger point, the maintainers of this repo need to be onboard with supporting v2 and to drive the solution. I have no cycles or the expertise to make decisions and changes.

**Comment by paulkre** [comment]
I would also be happy to see 4.0.0 get released in the `https://jaegertracing.github.io/helm-charts` repository, because it is currently very annoying to setup 4.0.0 as a chart dependency and this is the only easy way to deploy Jaeger v2.

**Comment by jfshark** [comment]
@paulkre can I ask you, please, to elaborate more on how to setup 4.0.0 as a chart dependency to easily deploy Jaeger v2. I can't figure it out.

**Comment by paulkre** [comment]
I gave up on integrating it as a dependency and just wrote my own template instead. Turned out to be much easier for my use case.

```yaml
{{- $podName := printf "%s-jaeger" .Release.Name -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-jaeger-collector
spec:
  type: ClusterIP
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 0
      appProtocol: grpc
    - name: otlp-http
      port: 4318
      targetPort: 0
      appProtocol: http
  selector:
    app: {{ $podName }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-jaeger-query
spec:
  type: ClusterIP
  ports:
    - name: http-query
      port: 16686
      targetPort: 16686
    - name: grpc-query
      port: 16685
      targetPort: 16685
    - name: http-metrics
      port: 8888
      targetPort: 8888
  selector:
    app: {{ $podName }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $podName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $podName }}
  template:
    metadata:
      name: {{ $podName }}
      labels:
        app: {{ $podName }}
    spec:
      containers:
        - name: main
          image: jaegertracing/jaeger
          imagePullPolicy: Always
          ports:
            - containerPort: 5775
              protocol: UDP
            - containerPort: 6831
              protocol: UDP
            - containerPort: 6832
              protocol: UDP
            - containerPort: 5778
              protocol: TCP
            - containerPort: 16686
              protocol: TCP
            - containerPort: 16685
              protocol: TCP
            - containerPort: 8888
              protocol: TCP
            - containerPort: 9411
              protocol: TCP
            - containerPort: 4317
              protocol: TCP
            - containerPort: 4318
              protocol: TCP
            - containerPort: 13133
              protocol: TCP
```
