### ISSUE TITLE
[Feature]: Ability to set metrics port

### ISSUE THREAD

**Issue by miroslavmasaryk3221** [jaegertracing/helm-charts#611]
### Requirement

Requirement
As a jaeger helm chart user, I would like to change exporter port with name admin for all microservices e.g agent to a custom one

### Problem

In our environment we need to change it to 9100 for telegraf, because of specific usecase, telegraf config cannot be adopted.
So solution would be to change admin port  and also adjust exporter configuration.

```
ports:
- name: zipkin-compact
  containerPort: {{ .Values.agent.service.zipkinThriftPort }}
  protocol: UDP
  {{- if .Values.agent.daemonset.useHostPort }}
  hostPort: {{ .Values.agent.service.zipkinThriftPort }}
  {{- end }}
- name: jaeger-compact
  containerPort: {{ .Values.agent.service.compactPort }}
  protocol: UDP
  {{- if .Values.agent.daemonset.useHostPort }}
  hostPort: {{ .Values.agent.service.compactPort }}
  {{- end }}
- name: jaeger-binary
  containerPort: {{ .Values.agent.service.binaryPort }}
  protocol: UDP
  {{- if .Values.agent.daemonset.useHostPort }}
  hostPort: {{ .Values.agent.service.binaryPort }}
  {{- end }}
- name: http
  containerPort: {{ .Values.agent.service.samplingPort }}
  protocol: TCP
  {{- if .Values.agent.daemonset.useHostPort }}
  hostPort: {{ .Values.agent.service.samplingPort }}
  {{- end }}
- name: admin
  # here this should be changed 
  containerPort: 14271
  protocol: TCP
```

### Proposal

Example for agent
```
ports:
- name: zipkin-compact
  containerPort: {{ .Values.agent.service.zipkinThriftPort }}
  protocol: UDP
  {{- if .Values.agent.daemonset.useHostPort }}
  hostPort: {{ .Values.agent.service.zipkinThriftPort }}
  {{- end }}
- name: jaeger-compact
  containerPort: {{ .Values.agent.service.compactPort }}
  protocol: UDP
  {{- if .Values.agent.daemonset.useHostPort }}
  hostPort: {{ .Values.agent.service.compactPort }}
  {{- end }}
- name: jaeger-binary
  containerPort: {{ .Values.agent.service.binaryPort }}
  protocol: UDP
  {{- if .Values.agent.daemonset.useHostPort }}
  hostPort: {{ .Values.agent.service.binaryPort }}
  {{- end }}
- name: http
  containerPort: {{ .Values.agent.service.samplingPort }}
  protocol: TCP
  {{- if .Values.agent.daemonset.useHostPort }}
  hostPort: {{ .Values.agent.service.samplingPort }}
  {{- end }}
- name: admin
  # here this should be changed 
  containerPort: {{ .Values.agent.service.metricsPort }}
  protocol: TCP
```

### Open questions

Nothing
