### ISSUE TITLE
[Bug]: [jaeger] can't affect storage.elasticseach.host value

### ISSUE THREAD

**Issue by s-dwinter** [jaegertracing/helm-charts#632]
### What happened?

I have been customizing the elasticsearch hostname using the jaeger helm chart by specifying the `storage.elasticsearch.host` variable. However, since version 3.3.2, the value I provided is being overwritten with a different one. I suspect this is due to changes introduced in the following section in v3.3.2.

https://github.com/jaegertracing/helm-charts/blob/9c9abf46461612ef3f2a11149200a45b35c9a82c/charts/jaeger/templates/_helpers.tpl#L272-L274

I believe there are users, like myself, who customize the hostname, so I think `$host` should not be overwritten.

### Steps to reproduce

You use this `values.yaml` and use jaeger helm chart newer than `3.3.2` version.

```yaml
provisionDataStore:
  cassandra: false
  elasticsearch: true

storage:
  type: elasticsearch

  elasticsearch:
    host: custom-host
```

### Expected behavior

The value specified for `storage.elasticsearch.host` to be reflected in the manifests.

### Relevant log output

```shell

```

### Deployment configs

```shell

```
