### ISSUE TITLE
[Bug]: esIndexCleaner does not use the right indexPrefix

### ISSUE THREAD

**Issue by bbakker2** [jaegertracing/helm-charts#634]
### What happened?

The Helm chart configures Elasticsearch index cleaner cronjob with environment variable `ES_INDEX_PREFIX` to set the Elasticsearch index prefix. 
The cleaner (`jaegertracing/jaeger-es-index-cleaner:1.53.0`) however, expects this in environment variable `INDEX_PREFIX`. 
Result: the cleaner fails to find an clean the Jaeger indices.  

### Steps to reproduce

1. configure the jaeger Helm chart with 
```
storage:
  type: elasticsearch
  elasticsearch:
    indexPrefix: my-prefix

esIndexCleaner:
   enabled: true
```
2. trigger the index cleaner cronjob
3. in the log (see attached log output), observe that it does not find any indices.

### Expected behavior

I cleaning of jaeger indices, based on the configured prefix

### Relevant log output

```shell
{"level":"info","ts":1741169230.143658,"caller":"es-index-cleaner/main.go:89","msg":"Indices before this date will be deleted","date":"2025-03-01T00:00:00Z"}
{"level":"info","ts":1741169230.1437361,"caller":"es-index-cleaner/main.go:98","msg":"Queried indices","indices":null}
{"level":"info","ts":1741169230.1438448,"caller":"es-index-cleaner/main.go:102","msg":"No indices to delete"}
```

### Additional context

A workaround is to set `INDEX_PREFIX` in the the cleaner job
```
esIndexCleaner:
  enabled: true
  extraEnv:
  - name: INDEX_PREFIX
    value: my-prefix
```

Related: https://github.com/jaegertracing/jaeger/issues/3228#issuecomment-918259378

### Jaeger backend version

1.53.0

### Stogage backend

Elasticsearch 8 (on premise)

### Operating system

Linux

### Deployment model

Kubernetes

### Deployment configs

```shell

```
