### ISSUE TITLE
[jaeger] cmdlineParams uses the wrong format ?

### ISSUE THREAD

**Issue by eddycharly** [jaegertracing/helm-charts#90]
I tried to set `cmdlineParams` in the collector like this:
```yaml
collector:
  cmdlineParams:
    es.num-shards: 2
    es.num-replicas: 0
```

Now the collector refuses to start with the error: `Error: invalid argument "--es.num-shards=2" for "--es.num-replicas" flag: parse error`

It looks like arguments are expected to be separated by a space rather than a `=`.

Is the code below supposed to work with `--es.num-shards` and `--es.num-replicas` ?

https://github.com/jaegertracing/helm-charts/blob/f8e9b6946e31ddb2b7dde7b3025bf04b1e6b08aa/charts/jaeger/templates/collector-deploy.yaml#L46-L53
